name: Memory-Maze CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ make

    - name: Compile the project
      run: g++ Memory-Maze-Project/main.cpp -o maze  

    - name: Run the maze 
      run: ./maze  
